In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir('C:\\Users\\DELL\\Desktop\\Data Framing\\')

In [3]:
dataset = pd.read_csv('voice.csv')

In [4]:
dataset

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
5     0.132786  0.079557  0.119090  0.067958  0.209592  0.141634   1.932562   
6     0.150762  0.074463  0.160106  0.092899  0.205718  0.112819   1.530643   
7     0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   1.397156   
8     0.142239  0.078018  0.138587  0.088206  0.208587  0.120381   1.099746   
9     0.134329  0.080350  0.121451  0.075580  0.201957  0.126377   1.190368   
10    0.157021  0.071943  0.168160  0.101430  0.216740  0.115310   0.979442   
11    0.138551  0.077054  0.127527  0.087314  0.202739  0.115426   1.626770   
12    0.137343  0.080877  0.124263  0.083145  0.209227  0.126082   1.378728   
13    0.181225  0.060042  0.190953  0.128839  0.229532  0.100693   1.369430   
14    0.183115  0.066982  0.191233  0.129149  0.240152  0.111004   3.568104   
15    0.174272  0.069411  0.190874  0.115602  0.228279  0.112677   4.485038   
16    0.190846  0.065790  0.207951  0.132280  0.244357  0.112076   1.562304   
17    0.171247  0.074872  0.152807  0.122391  0.243617  0.121227   3.207170   
18    0.168346  0.074121  0.145618  0.115756  0.239824  0.124068   2.704335   
19    0.173631  0.073352  0.153569  0.123680  0.244234  0.120554   2.804975   
20    0.172754  0.076903  0.177736  0.120070  0.245368  0.125298   2.967765   
21    0.181015  0.074369  0.169299  0.128673  0.254175  0.125502   2.587325   
22    0.163536  0.072449  0.145543  0.113930  0.227449  0.113519   3.587650   
23    0.170213  0.075105  0.146053  0.123989  0.250126  0.126137   2.816793   
24    0.160422  0.076615  0.144824  0.120924  0.237244  0.116319   6.253208   
25    0.164700  0.075362  0.147018  0.118698  0.240475  0.121777   4.208608   
26    0.169579  0.075635  0.186468  0.116706  0.238549  0.121843   4.269923   
27    0.169021  0.071778  0.143168  0.125801  0.248315  0.122515   3.079273   
28    0.167340  0.072841  0.141739  0.122174  0.240000  0.117826   2.192126   
29    0.180528  0.070867  0.142385  0.129541  0.252477  0.122936   2.799969   
...        ...       ...       ...       ...       ...       ...        ...   
3138  0.114477  0.081973  0.090199  0.041095  0.199900  0.158806   1.103680   
3139  0.112769  0.074424  0.094248  0.049183  0.183235  0.134052   0.945953   
3140  0.126439  0.079412  0.127325  0.046889  0.198993  0.152103   1.452173   
3141  0.117350  0.090035  0.109478  0.024017  0.203946  0.179929   2.610623   
3142  0.104793  0.085201  0.077886  0.028388  0.186101  0.157712   2.419127   
3143  0.127633  0.084931  0.158892  0.034531  0.201430  0.166899   1.591174   
3144  0.091250  0.086956  0.048191  0.015193  0.179043  0.163851   3.089787   
3145  0.082404  0.085136  0.035114  0.016920  0.152827  0.135906   2.570944   
3146  0.124695  0.080989  0.131882  0.042033  0.197268  0.155234   1.970756   
3147  0.131566  0.084354  0.131889  0.053093  0.196147  0.143055   2.243370   
3148  0.108888  0.092021  0.070063  0.022520  0.201180  0.178660   2.235435   
3149  0.090445  0.079045  0.059358  0.020893  0.167727  0.146834   2.187161   
3150  0.137507  0.091521  0.161298  0.043547  0.221260  0.177713   1.119608   
3151  0.113148  0.090335  0.084335  0.026622  0.198830  0.172207   2.258273   
3152  0.149731  0.082852  0.180932  0.060212  0.219788  0.159576   1.240037   
3153  0.189614  0.035933  0.194116  0.168434  0.205289  0.036855   2.724415   
3154  0.200097  0.045533  0.203796  0.176581  0.232133  0.055552   1.160197   
3155  0.178573  0.046679  0.164388  0.149309  0.204601  0.055293   3.066668   
3156  0.201806  0.036057  0.201622  0.178165  0.227872  

In [6]:
dataset.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [7]:
x = dataset.iloc[:,:-1].values
pd.DataFrame(x)

0         1         2         3         4         5          6   \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
5     0.132786  0.079557  0.119090  0.067958  0.209592  0.141634   1.932562   
6     0.150762  0.074463  0.160106  0.092899  0.205718  0.112819   1.530643   
7     0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   1.397156   
8     0.142239  0.078018  0.138587  0.088206  0.208587  0.120381   1.099746   
9     0.134329  0.080350  0.121451  0.075580  0.201957  0.126377   1.190368   
10    0.157021  0.071943  0.168160  0.101430  0.216740  0.115310   0.979442   
11    0.138551  0.077054  0.127527  0.087314  0.202739  0.115426   1.626770   
12    0.137343  0.080877  0.124263  0.083145  0.209227  0.126082   1.378728   
13    0.181225  0.060042  0.190953  0.128839  0.229532  0.100693   1.369430   
14    0.183115  0.066982  0.191233  0.129149  0.240152  0.111004   3.568104   
15    0.174272  0.069411  0.190874  0.115602  0.228279  0.112677   4.485038   
16    0.190846  0.065790  0.207951  0.132280  0.244357  0.112076   1.562304   
17    0.171247  0.074872  0.152807  0.122391  0.243617  0.121227   3.207170   
18    0.168346  0.074121  0.145618  0.115756  0.239824  0.124068   2.704335   
19    0.173631  0.073352  0.153569  0.123680  0.244234  0.120554   2.804975   
20    0.172754  0.076903  0.177736  0.120070  0.245368  0.125298   2.967765   
21    0.181015  0.074369  0.169299  0.128673  0.254175  0.125502   2.587325   
22    0.163536  0.072449  0.145543  0.113930  0.227449  0.113519   3.587650   
23    0.170213  0.075105  0.146053  0.123989  0.250126  0.126137   2.816793   
24    0.160422  0.076615  0.144824  0.120924  0.237244  0.116319   6.253208   
25    0.164700  0.075362  0.147018  0.118698  0.240475  0.121777   4.208608   
26    0.169579  0.075635  0.186468  0.116706  0.238549  0.121843   4.269923   
27    0.169021  0.071778  0.143168  0.125801  0.248315  0.122515   3.079273   
28    0.167340  0.072841  0.141739  0.122174  0.240000  0.117826   2.192126   
29    0.180528  0.070867  0.142385  0.129541  0.252477  0.122936   2.799969   
...        ...       ...       ...       ...       ...       ...        ...   
3138  0.114477  0.081973  0.090199  0.041095  0.199900  0.158806   1.103680   
3139  0.112769  0.074424  0.094248  0.049183  0.183235  0.134052   0.945953   
3140  0.126439  0.079412  0.127325  0.046889  0.198993  0.152103   1.452173   
3141  0.117350  0.090035  0.109478  0.024017  0.203946  0.179929   2.610623   
3142  0.104793  0.085201  0.077886  0.028388  0.186101  0.157712   2.419127   
3143  0.127633  0.084931  0.158892  0.034531  0.201430  0.166899   1.591174   
3144  0.091250  0.086956  0.048191  0.015193  0.179043  0.163851   3.089787   
3145  0.082404  0.085136  0.035114  0.016920  0.152827  0.135906   2.570944   
3146  0.124695  0.080989  0.131882  0.042033  0.197268  0.155234   1.970756   
3147  0.131566  0.084354  0.131889  0.053093  0.196147  0.143055   2.243370   
3148  0.108888  0.092021  0.070063  0.022520  0.201180  0.178660   2.235435   
3149  0.090445  0.079045  0.059358  0.020893  0.167727  0.146834   2.187161   
3150  0.137507  0.091521  0.161298  0.043547  0.221260  0.177713   1.119608   
3151  0.113148  0.090335  0.084335  0.026622  0.198830  0.172207   2.258273   
3152  0.149731  0.082852  0.180932  0.060212  0.219788  0.159576   1.240037   
3153  0.189614  0.035933  0.194116  0.168434  0.205289  0.036855   2.724415   
3154  0.200097  0.045533  0.203796  0.176581  0.232133  0.055552   1.160197   
3155  0.178573  0.046679  0.164388  0.149309  0.204601  0.055293   3.066668   
3156  0.201806  0.036057  0.201622  0.178165  0.227872  0.0497

In [9]:
y = dataset.iloc[:,-1:].values
y

array([['male'],
       ['male'],
       ['male'],
       ...,
       ['female'],
       ['female'],
       ['female']], dtype=object)

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)

In [11]:
pd.DataFrame(x)

0         1         2         3         4         5         6   \
0    -4.049248  0.427355 -4.224901 -2.576102 -5.693607 -0.214778  2.293306   
1    -3.841053  0.611669 -3.999293 -2.486885 -5.588987 -0.258485  4.548056   
2    -3.463066  1.603848 -4.095851 -2.706986 -3.928699  0.909326  6.513656   
3    -0.992157  0.899998 -0.759454 -0.901418 -0.711205  0.632690 -0.449858   
4    -1.530640  1.322561 -1.676948 -1.268395 -0.792029  1.005588 -0.480911   
5    -1.608666  1.347232 -1.830062 -1.489512 -0.641972  1.340093 -0.284822   
6    -1.007728  1.041300 -0.701821 -0.977084 -0.805857  0.666485 -0.379617   
7    -0.681717  1.179662 -1.135596 -0.614797  0.304495  0.867778 -0.411101   
8    -1.292650  1.254833 -1.293742 -1.073498 -0.684457  0.843266 -0.481247   
9    -1.557104  1.394871 -1.765105 -1.332913 -0.964981  0.983436 -0.459874   
10   -0.798516  0.889928 -0.480286 -0.801809 -0.339540  0.724711 -0.509622   
11   -1.415970  1.196906 -1.597993 -1.091834 -0.931884  0.727416 -0.356945   
12   -1.456347  1.426504 -1.687778 -1.177487 -0.657408  0.976534 -0.415448   
13    0.010659  0.175145  0.146682 -0.238674  0.201692  0.383013 -0.417641   
14    0.073836  0.591989  0.154365 -0.232308  0.651033  0.624047  0.100932   
15   -0.221793  0.737860  0.144506 -0.510634  0.148688  0.663169  0.317197   
16    0.332285  0.520391  0.614239 -0.167964  0.828910  0.649118 -0.372150   
17   -0.322923  1.065826 -0.902615 -0.371152  0.797633  0.863030  0.015803   
18   -0.419905  1.020735 -1.100340 -0.507472  0.637139  0.929459 -0.102794   
19   -0.243212  0.974530 -0.881657 -0.344662  0.823720  0.847302 -0.079057   
20   -0.272533  1.187812 -0.216876 -0.418836  0.871679  0.958198 -0.040662   
21    0.003637  1.035660 -0.448965 -0.242078  1.244304  0.962969 -0.130392   
22   -0.580707  0.920317 -1.102429 -0.544994  0.113546  0.682848  0.105542   
23   -0.357496  1.079843 -1.088387 -0.338321  1.072984  0.977815 -0.076270   
24   -0.684788  1.170525 -1.122199 -0.401289  0.527958  0.748315  0.734232   
25   -0.541795  1.095269 -1.061830 -0.447018  0.664676  0.875888  0.251999   
26   -0.378690  1.111650  0.023296 -0.487942  0.583212  0.877440  0.266461   
27   -0.397338  0.880031 -1.167732 -0.301099  0.996389  0.893142 -0.014362   
28   -0.453526  0.943881 -1.207049 -0.375609  0.644582  0.783535 -0.223602   
29   -0.012663  0.825306 -1.189274 -0.224242  1.172476  0.902986 -0.080238   
...        ...       ...       ...       ...       ...       ...       ...   
3138 -2.220763  1.492334 -2.624762 -2.041441 -1.051994  1.741539 -0.480319   
3139 -2.277843  1.038917 -2.513376 -1.875257 -1.757085  1.162862 -0.517521   
3140 -1.820866  1.338525 -1.603546 -1.922388 -1.090411  1.584852 -0.398125   
3141 -2.124724  1.976562 -2.094450 -2.392307 -0.880846  2.235330 -0.124897   
3142 -2.544487  1.686205 -2.963466 -2.302500 -1.635860  1.715972 -0.170062   
3143 -1.780943  1.670021 -0.735229 -2.176296 -0.987289  1.930734 -0.365341   
3144 -2.997235  1.791664 -3.780265 -2.573615 -1.934450  1.859471 -0.011883   
3145 -3.292965  1.682342 -4.139992 -2.538121 -3.043655  1.206207 -0.134255   
3146 -1.879171  1.433258 -1.478176 -2.022152 -1.163387  1.658043 -0.275814   
3147 -1.649465  1.635349 -1.478006 -1.794933 -1.210781  1.373320 -0.211516   
3148 -2.407578  2.095875 -3.178655 -2.423065 -0.997876  2.205664 -0.213387   
3149 -3.024152  1.316492 -3.473093 -2.456503 -2.413243  1.461666 -0.224773   
3150 -1.450845  2.065806 -0.669031 -1.991063 -0.148305  2.183541 -0.476563   
3151 -2.265190  1.994577 -2.786060 -2.338782 -1.097295  2.054831 -0.208001   
3152 -1.042208  1.545145 -0.128966 -1.648662 -0.210565  1.759547 -0.448159   
3153  0.291089 -1.272904  0.233668  0.574827 -0.824017 -1.109355 -0.098058   
3154  0.641537 -0.696280  0.499961  0.742219  0.311721 -0.672279 -0.466990   
3155 -0.078030 -0.627479 -0.584039  0.181889 -0.853117 -0.678339 -0.017335   
3156  0.698665 -1.265427  0.440157  0.774763  0.131471 -0.808904 -0.366714   
3157  0.759536 -0.936800  0.508424

In [57]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
# Classification_Logistic_Regression_Algorithm

In [79]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [81]:
y_pred = logmodel.predict(x_test)
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'male', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
      

In [82]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[292,  16],
       [  8, 318]], dtype=int64)

In [ ]:
# Classification_K-Neighbors_Classifier_Algorithm

In [85]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, 
                                      metric='minkowski', p=2)
classifier_knn.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [86]:
y_pred = classifier_knn.predict(x_test)
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female',
       'female', 'female', 'male', 'female', 'male', 'female', 'female',
       'male', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'female', 'male', 'female', 'female', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
  

In [87]:
confusion_matrix(y_test, y_pred)

array([[298,  10],
       [  7, 319]], dtype=int64)

In [ ]:
# Classification_Naive_Bayes_Algorithm

In [88]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)


C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [89]:
y_pred=classifier_nb.predict(x_test)
y_pred


array(['female', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'female', 'female',
       'female', 'male', 'male', 'female', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'female', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'male', 'female',
       'male', 'female', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'female', 'male', 'male', 'male', 'male',
       'female', 'fema

In [90]:
confusion_matrix(y_test, y_pred)

array([[264,  44],
       [ 32, 294]], dtype=int64)

In [ ]:
# Classification_SVC(Support Vector Machine)_Algorithm:-kernel='sigmoid'

In [58]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='sigmoid')
classifier_svm.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [59]:
y_pred = classifier_svm.predict(x_test)


In [60]:
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'female', 'female', 'male', 'male', 'female',
       'female', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'female',
       'male', 'female', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'female', 'female', 'female',
       'female', 'male', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'female', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
    

In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[246,  62],
       [ 64, 262]], dtype=int64)

In [ ]:
# Classification_SVC(Support Vector Machine)_Algorithm:-kernel='linear'

In [62]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='linear')
classifier_svm.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [63]:
y_pred = classifier_svm.predict(x_test)

In [64]:
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
    

In [65]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[298,  10],
       [  8, 318]], dtype=int64)

In [ ]:
# Classification_SVC(Support Vector Machine)_Algorithm:-kernel='rbf'

In [91]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [92]:
y_pred = classifier_svm_rbf.predict(x_test)

In [93]:
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'female',
       'female', 'female', 'male', 'female', 'male', 'female', 'female',
       'male', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'female', 'male', 'female', 'female', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female'

In [94]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[303,   5],
       [ 10, 316]], dtype=int64)

In [ ]:
# Classification_Decision_Tree_Classification_Algorithm

In [70]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [74]:
y_pred = classifier_dt.predict(x_test)
y_pred

array(['female', 'female', 'male', 'female', 'male', 'female', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'female', 'male', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'male', 'female',
       'female', 'male', 'female', 'male', 'female', 'female', 'male',
       'female', 'male', 'female', 'male', 'female', 'female', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'female',
       'female

In [75]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[298,  10],
       [  8, 318]], dtype=int64)

In [ ]:
# Classification_Random_Forest_Classification_Algorithm

In [76]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [77]:
y_pred = classifier_rf.predict(x_test)

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[299,   9],
       [ 11, 315]], dtype=int64)

In [95]:
y_pred = classifier_svm_rbf.predict(x)

In [98]:
y_pred_D= pd.DataFrame(y_pred)

In [105]:
y_pred_D= y_pred_D.rename(columns={0:'label'})

In [106]:
y_pred_D

label
0       male
1       male
2       male
3       male
4       male
5       male
6       male
7       male
8       male
9       male
10      male
11      male
12      male
13      male
14      male
15      male
16      male
17      male
18      male
19      male
20      male
21      male
22      male
23      male
24      male
25      male
26      male
27      male
28      male
29      male
...      ...
3138  female
3139  female
3140  female
3141  female
3142  female
3143  female
3144  female
3145  female
3146  female
3147  female
3148  female
3149  female
3150  female
3151  female
3152  female
3153  female
3154  female
3155  female
3156  female
3157  female
3158  female
3159  female
3160  female
3161  female
3162  female
3163  female
3164  female
3165  female
3166  female
3167  female

[3168 rows x 1 columns]

In [102]:
dataset_new = dataset.drop(['label'], axis=1)

In [110]:
dataset_new_Classification = pd.concat([dataset_new, y_pred_D], axis=1)

In [111]:
dataset_new_Classification

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
5     0.132786  0.079557  0.119090  0.067958  0.209592  0.141634   1.932562   
6     0.150762  0.074463  0.160106  0.092899  0.205718  0.112819   1.530643   
7     0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   1.397156   
8     0.142239  0.078018  0.138587  0.088206  0.208587  0.120381   1.099746   
9     0.134329  0.080350  0.121451  0.075580  0.201957  0.126377   1.190368   
10    0.157021  0.071943  0.168160  0.101430  0.216740  0.115310   0.979442   
11    0.138551  0.077054  0.127527  0.087314  0.202739  0.115426   1.626770   
12    0.137343  0.080877  0.124263  0.083145  0.209227  0.126082   1.378728   
13    0.181225  0.060042  0.190953  0.128839  0.229532  0.100693   1.369430   
14    0.183115  0.066982  0.191233  0.129149  0.240152  0.111004   3.568104   
15    0.174272  0.069411  0.190874  0.115602  0.228279  0.112677   4.485038   
16    0.190846  0.065790  0.207951  0.132280  0.244357  0.112076   1.562304   
17    0.171247  0.074872  0.152807  0.122391  0.243617  0.121227   3.207170   
18    0.168346  0.074121  0.145618  0.115756  0.239824  0.124068   2.704335   
19    0.173631  0.073352  0.153569  0.123680  0.244234  0.120554   2.804975   
20    0.172754  0.076903  0.177736  0.120070  0.245368  0.125298   2.967765   
21    0.181015  0.074369  0.169299  0.128673  0.254175  0.125502   2.587325   
22    0.163536  0.072449  0.145543  0.113930  0.227449  0.113519   3.587650   
23    0.170213  0.075105  0.146053  0.123989  0.250126  0.126137   2.816793   
24    0.160422  0.076615  0.144824  0.120924  0.237244  0.116319   6.253208   
25    0.164700  0.075362  0.147018  0.118698  0.240475  0.121777   4.208608   
26    0.169579  0.075635  0.186468  0.116706  0.238549  0.121843   4.269923   
27    0.169021  0.071778  0.143168  0.125801  0.248315  0.122515   3.079273   
28    0.167340  0.072841  0.141739  0.122174  0.240000  0.117826   2.192126   
29    0.180528  0.070867  0.142385  0.129541  0.252477  0.122936   2.799969   
...        ...       ...       ...       ...       ...       ...        ...   
3138  0.114477  0.081973  0.090199  0.041095  0.199900  0.158806   1.103680   
3139  0.112769  0.074424  0.094248  0.049183  0.183235  0.134052   0.945953   
3140  0.126439  0.079412  0.127325  0.046889  0.198993  0.152103   1.452173   
3141  0.117350  0.090035  0.109478  0.024017  0.203946  0.179929   2.610623   
3142  0.104793  0.085201  0.077886  0.028388  0.186101  0.157712   2.419127   
3143  0.127633  0.084931  0.158892  0.034531  0.201430  0.166899   1.591174   
3144  0.091250  0.086956  0.048191  0.015193  0.179043  0.163851   3.089787   
3145  0.082404  0.085136  0.035114  0.016920  0.152827  0.135906   2.570944   
3146  0.124695  0.080989  0.131882  0.042033  0.197268  0.155234   1.970756   
3147  0.131566  0.084354  0.131889  0.053093  0.196147  0.143055   2.243370   
3148  0.108888  0.092021  0.070063  0.022520  0.201180  0.178660   2.235435   
3149  0.090445  0.079045  0.059358  0.020893  0.167727  0.146834   2.187161   
3150  0.137507  0.091521  0.161298  0.043547  0.221260  0.177713   1.119608   
3151  0.113148  0.090335  0.084335  0.026622  0.198830  0.172207   2.258273   
3152  0.149731  0.082852  0.180932  0.060212  0.219788  0.159576   1.240037   
3153  0.189614  0.035933  0.194116  0.168434  0.205289  0.036855   2.724415   
3154  0.200097  0.045533  0.203796  0.176581  0.232133  0.055552   1.160197   
3155  0.178573  0.046679  0.164388  0.149309  0.204601  0.055293   3.066668   
3156  0.201806  0.036057  0.201622  0.178165  0.227872  

In [112]:
dataset_new_Classification.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [113]:
dataset_new_Classification.to_csv('Output_Classification.csv')